baseURL = ''
#relativeURLs = true
languageCode = 'es'
title = 'Mi 1ยบ sitio en Hugo'
theme = "ananke"

#[[module.mounts]]
#source = 'static'
#target = 'static'

#[[module.mounts]]
#source = 'images'
#target = 'static/images'

[menu]
[[menu.main]]
	identifier = 'about'
	name = 'About us'
	url = '/about/'
[[menu.main]]
	identifier = 'posts'
	name = 'Posts'
	url = '/posts/'


[params]
	social = true